### ISSUE TITLE
useReactRouter may only be called within a <Router /> context

### ISSUE THREAD

**Issue by SaketSaxena** [CharlesStover/use-react-router#21]
After updating to react-router-dom to 5.0.1 from 5.0.0 I am getting this error.

```
bundle.js:70 Error: useReactRouter may only be called within a <Router /> context.
    at Object.<anonymous> (bundle.js:1)
    at r (bundle.js:1)
    at Module.<anonymous> (bundle.js:97)
    at r (bundle.js:1)
    at Object.<anonymous> (bundle.js:54)
    at r (bundle.js:1)
    at bundle.js:1
    at bundle.js:1
```

**Comment by quisido** [comment]
The [router context appears to still be exposed in 5.0.1](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/index.js#L35). Did you also upgrade your `react-router-dom` installation to the same version? Or are you using something other than `react-router-dom`?

This can also occur if you are creating a dependency package with `react-router-dom` defined as a peer dependency/external Webpack module while `react-router` is _not_ defined as a peer dependency or external Webpack module (it should be).

**Comment by gperl27** [comment]
Ran into the same issue on a brand new CRA with `react-router-dom` 5.0.1 installed.

I noticed the hook throws the error if it's declared at the same level where the `Router` is declared. But, it will work if it's in a separate component.

```
// error
const App = () => {
  const { history } = useReactRouter();

  return (
     <Router>
          <header>
              <button onClick={() => history.push('/about')}>click</button>
          </header>
          <Route path="/" exact component={Index}/>
          <Route path="/about" component={About}/>
     </Router>
   )
}

// good
const App = () => {

  const Head = () => {
    const { history } = useReactRouter();

    return (
          <header>
              <button onClick={() => history.push('/about')}>click</button>
          </header>
     )
  }

  return (
     <Router>
          <Head/>
          <Route path="/" exact component={Index}/>
          <Route path="/about" component={About}/>
     </Router>
   )
}
```

**Comment by SaketSaxena** [comment]
I used the hook inside the Component which is opened by the Route. Then also I am facing the issue

**Comment by gperl27** [comment]
Curious what your implementation looks like. The error makes sense after looking at the code as it's just calling `useContext`. A possible solution might be to pull the `Router` declaration to a top-level `index.js` or `App.js` (wherever you declare other providers or global setup).

**Comment by quisido** [comment]
Closing this as a `wontfix`. Either the issue is using the hook in the same component that mounts the router, or bug fixes can be migrated to React Router's official hook implementation.

Thanks for the contributions!
